### ISSUE TITLE
"rose-pine-emacs" is not available anymore

### ISSUE THREAD

**Issue by ghost** [jeetelongname/dotfiles#2]
I was trying out your `doom` config. Running `doom sync` returns an error.
![image](https://user-images.githubusercontent.com/80624167/167101560-405df886-2556-4315-bd08-55259a8b64e5.png)

I went to check out the repo and find out that "Caelie/rose-pine-emacs" does not exist anymore.

**Comment by jeetelongname** [comment]
imma close this because its really outta date
